language: node_js

node_js:
   - "12"

sudo: required

services:
  - docker

cache:
  directories:
    - ./node_modules

branches:
   only:
      - master

before_script:
   - npm install -g @angular/cli

script:
   - ng build --prod
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker build -t openhistorymap/ohm-digitizer:latest -t openhistorymap/ohm-digitizer:0.1.$TRAVIS_BUILD_NUMBER . && docker push openhistorymap/ohm-digitizer:latest


notifications:
  slack:
    rooms:
      - ingmmo:SW0ahzRuwFIJKKAlQPzGRg0f#travisbuilds
